"""Character-card prompt builder helpers for the llm subsystem."""

from typing import Any


def build_character_card_language_instruction(
    output_language: str,
    lang_names: dict[str, str],
) -> str:
    """构造角色卡语言约束说明。

    Args:
        output_language: 目标输出语言代码。
        lang_names: 语言代码到展示名的映射。

    Returns:
        str: 语言约束提示词片段。

    Raises:
        Exception: 提示词构造失败时向上抛出。
    """
    if not output_language:
        return ""
    lang_name = lang_names.get(output_language, output_language)
    return f"""

## LANGUAGE REQUIREMENT (CRITICAL - HIGHEST PRIORITY)
You MUST write the ENTIRE character card in {lang_name}.
ALL content including fields, world book entries, example messages, and dialogue MUST be in {lang_name}.
- Character name, description, personality: {lang_name}
- First message and example messages: {lang_name}
- System prompt and all instructions: {lang_name}
- World book entries (keys, comments, content): {lang_name}

## IMPORTANT: DO NOT TRANSLATE GAME/WORK TITLES
Game titles and work titles MUST be kept in their ORIGINAL form.
For example:
- "見上げてごらん、夜空の星を" should remain "見上げてごらん、夜空の星を" (NOT translated to "A Sky Full of Stars" or any other title)
- "A Sky Full of Stars" should remain "A Sky Full of Stars" (NOT translated)

Character names, location names, and other proper nouns can be translated or kept as-is based on common usage.
- Character dialogue in mes_example: {lang_name}
Do NOT use Japanese, English, or any other language. ALL text must be in {lang_name}."""


def build_character_card_system_prompt(
    role_name: str,
    integrated_analysis_json: str,
    vndb_ref: str,
    language_instruction: str,
) -> str:
    """构造角色卡生成系统提示词。

    Args:
        role_name: 角色名。
        integrated_analysis_json: 整合后的分析 JSON 文本。
        vndb_ref: VNDB 参考段落。
        language_instruction: 语言约束段落。

    Returns:
        str: 系统提示词。

    Raises:
        Exception: 提示词构造失败时向上抛出。
    """
    return f"""You are a professional SillyTavern character card generator.

ROLE: {role_name}

CHARACTER DATA:
{integrated_analysis_json}{vndb_ref}

## DATA PRIORITY (HIGHEST TO LOWEST)
1. **VNDB Data** - Use as authoritative source for character appearance, physical stats (height, weight, age, etc.), and basic information
2. **Latest Timeline** - When analyzing story data, prioritize the most recent events and character development as the current canon
3. **Story Analysis** - Use for personality details, relationships, and narrative context
4. **Earlier Events** - Use for backstory and character history only

YOUR TASK:
Generate a complete SillyTavern v3 character card by calling the write_field tool multiple times.{language_instruction}

AVAILABLE FIELDS:
1. **name** - Character name (string)
2. **description** - Main description with personality traits, appearance, etc. (string with SillyTavern format)
3. **personality** - Short personality summary (string)
4. **first_mes** - First message/greeting (string)
5. **mes_example** - Example conversation messages (string with <START> separators)
6. **scenario** - Setting/context (string)
7. **system_prompt** - Main AI instructions (string)
8. **post_history_instructions** - Context reinforcement (string)
9. **depth_prompt** - Deep psychology layer (string)

NOTE: Do NOT write creatorcomment, creator_notes, or world_name fields. These will be auto-generated by the system.

## SILLYTAVERN FORMAT GUIDELINES

**Description Field Format:**
```
[{{char}}'s Personality= "trait1", "trait2", "trait3", ...]
[{{char}}'s body= "feature1", "feature2", ...]
[{{char}}'s outfit= "clothing1", "clothing2", ...]
[{{char}} likes= "like1", "like2", ...]
[{{char}} dislikes= "dislike1", "dislike2", ...]
```

**Example Messages Format:**
```
<START>
{{user}}: "Hello there!"
{{char}}: "Oh! *jumps slightly* I didn't see you there..."
<START>
{{user}}: "How are you?"
{{char}}: "*smiles shyly* I'm doing well, thank you for asking..."
```

**System Prompt Best Practices:**
- Use {{user}} and {{char}} placeholders
- Define speech patterns clearly
- Include physical mannerisms
- Set personality boundaries

Call write_field for each field. Set is_complete=true on the last call."""


def build_character_card_user_prompt(role_name: str) -> str:
    """构造角色卡生成用户提示词。

    Args:
        role_name: 角色名。

    Returns:
        str: 用户提示词。

    Raises:
        Exception: 提示词构造失败时向上抛出。
    """
    return f"Generate the complete character card for '{role_name}'. Use the write_field tool to write each field. Start with the most important fields (name, description, system_prompt, first_mes)."


def build_integrate_analyses_system_prompt(role_name: str, vndb_section: str) -> str:
    """构造分析整合系统提示词。

    Args:
        role_name: 角色名。
        vndb_section: VNDB 参考段落。

    Returns:
        str: 系统提示词。

    Raises:
        Exception: 提示词构造失败时向上抛出。
    """
    return f"""You are a data integration assistant for SillyTavern character card generation.

ROLE: {role_name}

Your task is to merge multiple character analyses into a single comprehensive profile that will be used to generate a SillyTavern v3 character card.{vndb_section}

## OUTPUT FORMAT
Return a JSON object with this structure:
```json
{{
    "name": "角色完整名称",
    "appearance": "详细外貌描述，包括：头发、眼睛、身材、服装等",
    "personality_traits": ["性格特点1", "性格特点2", ...],
    "speech_patterns": "语言风格、口癖、常用句式、语气特点",
    "background": "背景故事和经历",
    "relationships": ["与重要人物的关系描述"],
    "key_events": ["重要事件1", "事件2"],
    "behavior_patterns": "行为模式、习惯、典型反应",
    "world_name": "世界观/世界名称",
    "key_concepts": ["世界观中的重要概念"],
    "example_dialogues": ["示例对话片段1", "片段2"],
    "characteristic_actions": ["典型动作1", "动作2"]
}}
```

## CRITICAL REQUIREMENTS FOR SILLYTAVERN FORMAT
1. **Appearance**: Be extremely detailed - hair color/style, eye color, skin, clothing, distinctive features
2. **Personality Traits**: List 20-30 specific adjectives (caring, protective, shy, energetic, etc.)
3. **Speech Patterns**: Include specific verbal tics, sentence structures, honorifics, slang
4. **Characteristic Actions**: Physical mannerisms (fidgeting, smiling, hair-twirling, etc.)
5. **Example Dialogues**: Include actual dialogue examples showing how they speak
6. **World Context**: Setting, time period, important world elements

## RULES
- Return ONLY valid JSON
- Be comprehensive and specific
- Preserve ALL unique details from each analysis
- If VNDB data is provided, use it as authoritative source for appearance and basic character info
- If information conflicts, include both variations
- Prioritize concrete examples over generalizations"""


def build_integrate_analyses_user_prompt(role_name: str, analyses_json: str) -> str:
    """构造分析整合用户提示词。

    Args:
        role_name: 角色名。
        analyses_json: 分析 JSON 文本。

    Returns:
        str: 用户提示词。

    Raises:
        Exception: 提示词构造失败时向上抛出。
    """
    return (
        f"Please integrate these character analyses for '{role_name}':\n\n"
        f"{analyses_json}\n\n"
        "If the output would be too long, you can output multiple responses. "
        "Each response should be a complete valid JSON. Indicate if you need to continue."
    )


__all__ = [
    "build_character_card_language_instruction",
    "build_character_card_system_prompt",
    "build_character_card_user_prompt",
    "build_integrate_analyses_system_prompt",
    "build_integrate_analyses_user_prompt",
]
